mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
  redis:
    host: 121.36.29.50
    port: 6666

# service version
wehouse:
  service:
    version: 1.0.0

# Dubbo Config properties
dubbo:
  application:
    id: wehouse-web
    name: wehouse-web
  registry:
    protocol: zookeeper
    address: 121.36.29.50:2181
  protocol:
    name: dubbo
    port: 20880
# web port
server:
  port: 9999

---
spring:
  profiles: uat
  redis:
    host: 127.0.0.1
    port: 6666

# service version
wehouse:
  service:
    version: 1.0.0

# Dubbo Config properties
dubbo:
  application:
    id: wehouse-web
    name: wehouse-web
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
# web port
server:
  port: 9999