mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  profiles:
    active: dev
  mail:
    host: smtp.163.com
    username: a1048733180@163.com
    password: 1swehouse

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wehouse?useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 6000
      stat-view-servlet:
        login-username: root
        login-password: wehouse
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1
  redis:
    host: 127.0.0.1
    port: 6379

# service version
wehouse:
  service:
    version: 1.0.dev

# Dubbo Config properties
dubbo:
  application:
    id: wehouse-service-dev
    name: wehouse-service-dev
  registry:
    protocol: zookeeper
    address: 121.36.29.50:2181
  protocol:
    name: dubbo
    port: 20881
# web port
server:
  port: 8888

---
spring:
  profiles: uat
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wehouse?useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 6000
      stat-view-servlet:
        login-username: root
        login-password: wehouse
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1
  redis:
    host: 127.0.0.1
    port: 6666

# service version
wehouse:
  service:
    version: 1.0

# Dubbo Config properties
dubbo:
  application:
    id: wehouse-service
    name: wehouse-service
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
# web port
server:
  port: 8888